DROP TABLE IF EXISTS fund_ledger;
DROP TABLE IF EXISTS penalties;
DROP TABLE IF EXISTS weeks;
DROP TABLE IF EXISTS checkins;
DROP TABLE IF EXISTS daily_polls;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS users;
